Initial version of Warning Tool plugin
editor-js/warning pull request #1
Opened 2018-10-31 17:43 UTC by PolinaShneider

2018-10-31 18:15 UTC, neSpecc requested changes

2018-10-31 18:15 UTC, neSpecc commented on README.md
> +Provides Warning Blocks for the [CodeX Editor](https://ifmo.su/editor).
Provides Warning Block for the CodeX Editor. Block has title and message. It can be used, for example, for editorials notifications or appeals.

2018-10-31 18:15 UTC, neSpecc commented on README.md
> +        titlePlaceholder: 'Enter warning title',
оставить просто Title и Message

2018-10-31 18:15 UTC, neSpecc commented on src/index.css
> +    margin: 0;
убрать

2018-10-31 18:15 UTC, neSpecc commented on src/index.js
> +    return `<svg width="16" height="17" viewBox="0 0 320 294" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M160.5 97c12.426 0 22.5 10.074 22.5 22.5v28c0 12.4
вынеси в файл и подключи через svg loader

2018-10-31 18:15 UTC, neSpecc commented on src/index.js
> +    return 'Warning alert';
Title

2018-10-31 18:15 UTC, neSpecc commented on src/index.js
> +    return 'Warning message';
Message

2018-10-31 18:15 UTC, neSpecc commented on src/index.js
> +   * data — previously saved data
объекты не так документируются

2018-10-31 18:15 UTC, neSpecc commented on src/index.js
> +
+ надо добавить sanitize config

2018-10-31 18:24 UTC, khaydarov requested changes

2018-10-31 18:24 UTC, khaydarov commented on README.md
> +| titlePlaceholder   | `string` | Warning Tool's title placeholder  |
и здесь title, message

2018-10-31 18:24 UTC, khaydarov commented on src/index.js
> + * @property {string} titlePlaceholder - placeholder to show in warning`s title input
и тут не забудь

2018-10-31 18:24 UTC, khaydarov commented on src/index.js
> +    return true;
почему контентлесс? там же будет текст

2018-10-31 18:24 UTC, khaydarov commented on src/index.js
> +   * @returns {{baseClass: string, wrapper: string, title: string, input: string, message: string}}
@returns {Object}

2018-10-31 18:26 UTC, neSpecc commented on src/index.js
> +    return true;
чтобы можно было выделить пустой блок

2018-11-02 09:27 UTC, neSpecc requested changes

2018-11-02 09:27 UTC, neSpecc commented on package.json
> +  "version": "2.0.0",
1.0.0

2018-11-08 07:49 UTC, neSpecc approved these changes

2018-11-10 17:07 UTC, khaydarov approved these changes

2018-11-11 09:34 UTC, merged