Add read-only mode support
editor-js/warning pull request #14
Opened 2020-08-22 22:28 UTC by gohabereg

2020-08-23 13:43 UTC, khaydarov approved these changes

2020-08-23 18:04 UTC, talyguryn requested changes

2020-08-23 18:04 UTC, talyguryn commented on src/index.js
>   */
код уехал, а коммент остался

2020-08-23 18:07 UTC, talyguryn approved these changes

2020-09-29 20:48 UTC, neSpecc approved these changes

2020-09-29 20:49 UTC, merged